AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: BChat backend powered by AWS SAM

Parameters:
  JwtSecret:
    Type: String
    Description: Secret key used to sign JWT tokens

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs20.x
    MemorySize: 256
    Architectures:
      - arm64
    Environment:
      Variables:
        JWT_SECRET: !Ref JwtSecret
        USERS_TABLE: UsersTable
        ROOMS_TABLE: RoomsTable
        MESSAGES_TABLE: MessagesTable

Resources:
  ##############################
  # SharedLayer
  ##############################

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: bchat-shared-layer
      Description: Common utilities for BChat (auth, db, etc)
      ContentUri: shared
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Delete

  ##############################
  # WebSocket API
  ##############################
  BChatWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: BChatWebSocketAPI
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  WebSocketHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/websocketHandler/
      Handler: app.handler
      Runtime: nodejs20.x
      MemorySize: 256
      Timeout: 10
      Layers:
        - !Ref SharedLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: "*"

  WebSocketIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BChatWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketHandlerFunction.Arn}/invocations
      IntegrationMethod: POST

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BChatWebSocketApi
      RouteKey: $connect
      Target: !Join ["/", ["integrations", !Ref WebSocketIntegration]]

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BChatWebSocketApi
      RouteKey: $disconnect
      Target: !Join ["/", ["integrations", !Ref WebSocketIntegration]]

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BChatWebSocketApi
      RouteKey: $default
      Target: !Join ["/", ["integrations", !Ref WebSocketIntegration]]

  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - DefaultRoute
    Properties:
      ApiId: !Ref BChatWebSocketApi

  BChatWebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: prod
      AutoDeploy: true
      DeploymentId: !Ref WebSocketDeployment
      ApiId: !Ref BChatWebSocketApi

  WebSocketInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketHandlerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BChatWebSocketApi}/*

  ##############################
  # HTTP REST API Functions
  ##############################

  UserHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/userHandler/
      Handler: app.handler
      Layers:
        - !Ref SharedLayer
      Events:
        User:
          Type: Api
          Properties:
            Path: /user
            Method: POST

  RoomHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/roomHandler/
      Handler: app.handler
      Layers:
        - !Ref SharedLayer
      Events:
        Room:
          Type: Api
          Properties:
            Path: /room
            Method: POST

  MessageHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/messageHandler/
      Handler: app.handler
      Layers:
        - !Ref SharedLayer
      Events:
        SendMessage:
          Type: Api
          Properties:
            Path: /message
            Method: POST
        GetMessage:
          Type: Api
          Properties:
            Path: /message
            Method: GET

  ##############################
  # DynamoDB Tables
  ##############################

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UsersTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

  RoomsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RoomsTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: roomId
          AttributeType: S
      KeySchema:
        - AttributeName: roomId
          KeyType: HASH

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MessagesTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: roomId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: roomId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

Outputs:
  WebSocketURL:
    Description: "WebSocket API URL"
    Value: !Sub "wss://${BChatWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/prod"

  UserHandlerFunctionURL:
    Description: "User Handler Function URL"
    Value: !Sub "https://${UserHandlerFunction}.execute-api.${AWS::Region}.amazonaws.com/Prod/user"

  RoomHandlerFunctionURL:
    Description: "Room Handler Function URL"
    Value: !Sub "https://${RoomHandlerFunction}.execute-api.${AWS::Region}.amazonaws.com/Prod/room"

  MessageHandlerFunctionURL:
    Description: "Message Handler Function URL"
    Value: !Sub "https://${MessageHandlerFunction}.execute-api.${AWS::Region}.amazonaws.com/Prod/message"
