AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: BChat backend powered by AWS SAM

Globals:
  Api:
    EndpointConfiguration: REGIONAL
  Function:
    Timeout: 10
    Runtime: nodejs20.x
    MemorySize: 256
    Architectures:
      - x86_64
    Environment:
      Variables:
        ROOMS_TABLE: RoomsTable

Resources:
  ##############################
  # WebSocket API
  ##############################
  BChatWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: BChatWebSocketAPI
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  WebSocketHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/websocketHandler/
      Handler: app.handler
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource: "*"

  WebSocketIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BChatWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketHandlerFunction.Arn}/invocations
      IntegrationMethod: POST

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BChatWebSocketApi
      RouteKey: $connect
      Target: !Join ["/", ["integrations", !Ref WebSocketIntegration]]

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BChatWebSocketApi
      RouteKey: $disconnect
      Target: !Join ["/", ["integrations", !Ref WebSocketIntegration]]

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BChatWebSocketApi
      RouteKey: $default
      Target: !Join ["/", ["integrations", !Ref WebSocketIntegration]]

  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - DefaultRoute
    Properties:
      ApiId: !Ref BChatWebSocketApi

  BChatWebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: prod
      AutoDeploy: true
      DeploymentId: !Ref WebSocketDeployment
      ApiId: !Ref BChatWebSocketApi

  WebSocketInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketHandlerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BChatWebSocketApi}/*

  ##############################
  # HTTP REST API Functions
  ##############################
  HttpRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,POST,GET'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  RoomHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/roomHandler/
      Handler: app.handler
      Events:
        Room:
          Type: Api
          Properties:
            RestApiId: !Ref HttpRestApi
            Path: /room
            Method: POST
            Auth:
              ApiKeyRequired: true

  ##############################
  # DynamoDB Tables
  ##############################

  RoomsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RoomsTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

Outputs:
  WebSocketURL:
    Description: "WebSocket API URL"
    Value: !Sub "wss://${BChatWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${BChatWebSocketStage}"

  RestApiUrl:
    Description: "Base URL for REST API (Stage: Prod)"
    Value: !Sub "https://${HttpRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
